---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
      - name: client
        image: client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: client
  name: client
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: client
  type: NodePort
