version: '2'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: 'password'
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data