version: '2'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

  gateway:
    build:
      context: ./
      dockerfile: ./Dockerfile.gateway-with-static-webclient.production
    command: yarn start
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      GATEWAY_URL: /
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_URL: postgresql://postgres:password@postgres:5432/postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENRECORD_POSTGRES_HOST: postgres
      OPENRECORD_POSTGRES_USER: postgres
      OPENRECORD_POSTGRES_PASSWORD: password
      OPENRECORD_POSTGRES_DATABASE: postgres
      PUSH_SUBSCRIPTION_ENCRYPTION_KEY: push_subscription_key
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    ports:
        - "6379:6379"
