# Build webclient
FROM webclient as builder
MAINTAINER Shain Lafazan
RUN mkdir -p /usr/share/webclient
RUN apt-get update
RUN mkdir /app
ADD ../webclient /usr/share/webclient
WORKDIR /usr/share/webclient
RUN yarn setup
RUN yarn build

# Run gateway
FROM node
RUN apt-get update
RUN mkdir /app
ADD . ./app
WORKDIR /app
RUN yarn install
CMD yarn migrate && yarn start
COPY --from=builder /app/dist/ /usr/share/app/
WORKDIR /app/
ADD . .
RUN yarn setup
CMD yarn start