# ---
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: 'shain.codes@gmail.com'
#     privateKeySecretRef:
#       name: letsencrypt-staging
#     http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'shain.codes@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}